
resolver: lts-6.9

packages:
    - '.'
    - location:
        git: https://github.com/Lokidottir/unify-terms
        commit: 2e71a392b8685488a566117fb42f75bd58411722
      extra-dep: true

extra-deps:
    - generic-random-0.3.0.0

flags: {}

extra-package-dbs: []
