
resolver: lts-6.9

packages:
    - '.'
    - location:
        git: https://github.com/Lokidottir/unify-terms
        commit: 2e71a392b8685488a566117fb42f75bd58411722
      extra-dep: true
    - location:
        git: git@github.com:Lokidottir/parameterized-typesystems.git
        commit: 17b6cfd0c9e5f335a546fefce52e77d3bce9139e
      extra-dep: true

extra-deps:
    - generic-random-0.3.0.0

flags: {}

extra-package-dbs: []
